image: resim_base_image:latest

stages:
  - build

build:
  stage: build
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - mkdir build
    - cd build && cmake .. -DRESIM_BUILD_TESTING=ON -GNinja
    - ninja -C . -j 4
    - ctest -V -j 2
