image:
  name: resim_base_image:v2
  pull_policy: never

stages:
  - build

build:
  stage: build
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - mkdir build
    - cd build && cmake .. -DRESIM_BUILD_TESTING=ON -GNinja
    - ninja -C .
    - ctest -V -j 5
