image: resim_base_image:latest

stages:
  - build

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - mkdir build
    - cd build && cmake .. -DRESIM_BUILD_TESTING=ON -DCMAKE_BULD_TYPE=Release -GNinja
    - ninja -C .
    - ctest -V -j 5